### ISSUE TITLE
is the state of this project current?

### ISSUE THREAD

**Issue by SimonHeimberg** [communitymedia/mediaphone-javame#1]
The last change of the project is from 2013. So is this version current anyway? Is it compatible to the current [mediaphone](https://github.com/communitymedia/mediaphone)?

I like the idea of using mediaphone without android!

**Comment by simonrob** [comment]
Thanks for your interest in this project!

This version of the app was originally designed for Symbian phones, with their comparatively limited functionality. You can take photos, add text and record audio, and export in a format that should be compatible with the current [mediaphone](https://github.com/communitymedia/mediaphone) (via the SMIL option). But, as you noted, this project hasn't been updated for many years, and I don't foresee it being updated again by me due to limited time and the much greater capabilities of the Android version.

If it's Google you're trying to avoid, you can use [F-Droid](https://f-droid.org/packages/ac.robinson.mediaphone/) instead. But if you really do want to totally remove any dependency on Android then please do feel free to use this project - let me know how you get on!

**Comment by SimonHeimberg** [comment]
I did instal it with F-Droid.
I am interested in editing on a computer. Guess I could use some android emulator.

**Comment by simonrob** [comment]
If you have a Chromebook the Android app should work as normal. It should also work in any Android emulator, with variable features depending on whether the emulator supports camera/audio. Another issue you might run into is with MP4 export, which will depend on the emulator's support for [MediaMuxer](https://developer.android.com/reference/android/media/MediaMuxer), but you should be able to change the app's settings and export to MOV instead if needed.

I'm closing this issue here as the discussion is now about the [mediaphone](https://github.com/communitymedia/mediaphone) project rather than this one, but feel free to open further issues over there and report back on how you get on.
